version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - ESP32_IP=192.168.86.90
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
    networks:
      - well-sensor-network

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - well-sensor-network

networks:
  well-sensor-network:
    driver: bridge 