version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8090:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
    networks:
      - well-sensor-network

  frontend:
    image: nginx:alpine
    ports:
      - "8091:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - well-sensor-network

networks:
  well-sensor-network:
    driver: bridge 
